- id: uncrustify
  name: uncrustify
  description: Run uncrustify on all files
  entry: python uncrustify_hook.py
  language: python
  types: [c, c++, c#, java]  # D, PAWN, OC, OC+, VALA.
  #files: \.(c|h|cpp|hpp|cc|hh|cxx|hxx)$
